### PR TITLE
Use ensure-docker in delivery.yaml

### PR DESCRIPTION
**Pull request by jmcs**
Use standardized way to install docker in CDP builds.

### CODE REVIEW

**Comment by harti2006** [comment]
@hjacobs started to use the docker via Ubuntu package manager. See [here](https://github.com/zalando-stups/docker-ubuntu/blob/master/delivery.yaml#L4) for example.

Wouldn't this be the even more "standardized" way?

**Comment by jmcs** [comment]
@harti2006 That's what [ensure-docker](https://delivery.cloud.zalando.com/utils/ensure-docker) does right now if docker is not installed already.

**Comment by harti2006** [comment]
:+1:

**Comment by jmcs** [comment]
:+1:

**Pull request merged**
